---
- name: Install and configure Wazuh Agent
  hosts: all
  become: true

  tasks:

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - gnupg
          - apt-transport-https
          - curl
        state: present
        update_cache: true

    - name: Install Wazuh GPG key
      ansible.builtin.shell:
        cmd: >
          curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH
          | gpg --no-default-keyring
          --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg
          --import
      args:
        creates: /usr/share/keyrings/wazuh.gpg

    - name: Set permissions on Wazuh GPG key
      ansible.builtin.file:
        path: /usr/share/keyrings/wazuh.gpg
        owner: root
        group: root
        mode: "0644"

    - name: Add Wazuh repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main"
        filename: wazuh
        state: present
        update_cache: true

    - name: Debug Wazuh variables
      ansible.builtin.debug:
        msg:
          - "Manager: {{ wazuh_manager }}"
          - "Version: {{ wazuh_agent_version }}"

    - name: Install Wazuh Agent
      ansible.builtin.apt:
        name: "wazuh-agent={{ wazuh_agent_version }}-1"
        state: present
      environment:
        WAZUH_MANAGER: "{{ wazuh_manager }}"

    - name: Enable and start Wazuh Agent
      ansible.builtin.systemd:
        name: wazuh-agent
        enabled: true
        state: started
        daemon_reload: true

    - name: Disable Wazuh repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main"
        filename: wazuh
        state: absent
        update_cache: true